/// Flutter icons CocktailMe
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CocktailMe
///      fonts:
///       - asset: fonts/CocktailMe.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CocktailMeIcons {
  CocktailMeIcons._();

  static const _kFontFam = 'CocktailMe';
  static const String? _kFontPkg = null;

  static const IconData logo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shot =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incognito =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whiskey =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
