name: domain
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
