name: domain
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../common/dependencies

  utils:
    path: ../libs/utils


dev_dependencies:
  flutter_test:
    sdk: flutter
  dev_dependencies:
    path: ../common/dev_dependencies
