name: domain
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: ../libs/utils

  uuid: ^4.1.0

  firebase_core: ^2.21.0
  firebase_analytics: ^10.7.0
  firebase_auth: ^4.12.1
  firebase_remote_config: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
