name: cocktail_me_app
description: App about cocktails
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../common/dependencies

  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  dev_dependencies:
    path: ../common/dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700

        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600

        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500

        - asset: fonts/quicksand/Quicksand-Regular.ttf
          weight: 400

        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
    - family: CocktailMe
      fonts:
        - asset: fonts/icons/CocktailMe.ttf
